.PHONY: clean mount umount reload
CFLAGS=-g -Wall -DDEBUG `pkg-config --cflags fuse` -DFUSE_USE_VERSION=29
LDFLAGS=-lfuse -lcurl

# EXE ]-------------------------------------------------------------------------

phpfs: main.o phpfs.o net.o $(patsubst %.c,%.o,$(wildcard fuse_api/*.c))

# OBJECTS ]---------------------------------------------------------------------

# generated by: gcc -D_FILE_OFFSET_BITS=64 -MM *.c
main.o: main.c phpfs.h debug.h net.h
net.o: net.c phpfs.h debug.h net.h
phpfs.o: phpfs.c phpfs.h debug.h net.h fuse_api/fuse_api.h

# UTILS ]-----------------------------------------------------------------------

clean:
	find -name '*.o' -delete
	rm -f ./phpfs

# TEST ]------------------------------------------------------------------------

mount:
	test -d /tmp/phpfs || mkdir /tmp/phpfs/
	./phpfs 'http://localhost/phpfs/phpfs.php' /tmp/phpfs/

umount:
	fusermount -u /tmp/phpfs/

reload: umount mount
